name: Migrate Travis to Github Actions
on:
  [push, pull_request]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: ${{ github.ref }}
    - name: Install Dependencies
      run: |
        pip install -r requirements/travis.txt
        pycodestyle .
        pylint tests
