name: Migrate Travis to Github Actions
on:
  [push, pull_request]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: enable-github-actions-demo
    - name: Install Dependencies
      run: |
        pip install -r requirements/travis.txt
        pycodestyle .
        pylint tests
